quizData = [
  {
    enunciated: `Acrescente uma "tooltip" ao parágrafo abaixo com o texto "Sobre Quizcode".`,
    question: `<p ***="Sobre Quizcode">Quizcode de quiz sobre programação.</p>`,
    a: "h1",
    b: "id",
    c: "class",
    d: "title",
    correct: "d",
  },
  {
    enunciated: `Ajuste o tamanho da imagem para 250 pixels de largura e 400 pixels de altura.`,
    question: `<img src="w3schools.jpg" width="***" height="***">`,
    a: "width=250, height=250",
    b: "width=400, height=250",
    c: "width=250, height=400",
    d: "width=400, height=400",
    correct: "c",
  },
  {
    enunciated: `Transforme o elemento abaixo em um link que vá para "https://www.quizcode.com.br".`,
    question: `<a ***="https://www.quizcode.com.br">Isso é um link.</a>`,
    a: "src",
    b: "href",
    c: "link",
    d: "script",
    correct: "b",
  },
  {
    enunciated: `Especificar um texto alternativo para a imagem. O texto alternativo é útil quando a imagem não pode ser exibida e também para acessibilidade.`,
    question: `<img src="quizcode.png" ***="Quizcode Logo">`,
    a: "text",
    b: "alt",
    c: "p",
    d: "inform",
    correct: "b",
  },
  {
    enunciated: `Use a tag HTML correta para adicionar um título com o texto "London".`,
    question: `<***>London</***>`,
    a: "h1",
    b: "title",
    c: "text",
    d: "p",
    correct: "a",
  },
  {
    enunciated: `Use a tag HTML correta para adicionar um parágrafo com o texto "Hello World!`,
    question: `<***>Hello World!</***>`,
    a: "h1",
    b: "title",
    c: "text",
    d: "p",
    correct: "d",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Utilize a etiqueta de comentário HTML para fazer um comentário a partir do texto "Isto é um comentário".`,
    question: `*** Isso é um comentário ***`,
    a: "<!-- -->",
    b: "<-- -->",
    c: "<!- -!>",
    d: "<-- ?-->",
    correct: "d",
  },
  {
    enunciated: `Utilize o HTML correto para tornar o texto abaixo em um link para "default.html".`,
    question: `<***>Visite nosso tutorial de HTML</***>`,
    a: '<a href="default"> </a>',
    b: '<a href="default.html"> </a>',
    c: '<a src="default.html"> </a>',
    d: '<a src="default"> </a>',
    correct: "b",
  },
  {
    enunciated: `Utilizar o atributo HTML correto para abrir numa nova janela.`,
    question: `<a href="html_images.asp" ***>HTML Images</a>`,
    a: 'target="_blank"',
    b: 'src="_blank"',
    c: 'target="_new"',
    d: 'src="new"',
    correct: "a",
  },
  {
    enunciated: `Utilizar os atributos de imagem HTML para definir o tamanho da imagem para 250 pixels de largura e 400 pixels de altura.`,
    question: `<img src="scream.png" ***="250" ***="400">`,
    a: "size size",
    b: "height width",
    c: "top left",
    d: "width height",
    correct: "d",
  },
  {
    enunciated: `Adicionar o atributo HTML correto para exibir a imagem "smiley.gif".`,
    question: `<img ***>`,
    a: 'src="smiley.gif"',
    b: 'src="smiley.png"',
    c: 'href="smiley.gif"',
    d: 'href="smiley"',
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
  {
    enunciated: `Acrescentar uma quebra de linha no meio do parágrafo:`,
    question: `<p>João foi ao parque.<***>João encontrou seu amigo lá.</p>`,
    a: "rb",
    b: "ul",
    c: "br",
    d: "li",
    correct: "c",
  },
];
